# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-11 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100, verbose_name='Application label')),
                ('model', models.CharField(max_length=100, verbose_name='Model name')),
                ('view', models.CharField(max_length=100, verbose_name='View name')),
                ('settings', models.TextField(blank=True, default=None, null=True, verbose_name='Settings')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Settings Display Model',
                'verbose_name': 'Settings Display Model',
            },
        ),
        migrations.AlterUniqueTogether(
            name='displaysettings',
            unique_together=set([('user_id', 'app_label', 'model', 'view')]),
        ),
    ]
